export const config = {
	api: {
		miningpoolhub: "https://cors-anywhere.herokuapp.com/https://miningpoolhub.com/index.php?page=api",
		price: "https://min-api.cryptocompare.com/data/pricemulti?tsyms=USD&fsyms=",
		icons: "https://min-api.cryptocompare.com/data/all/coinlist"
	},
	coins: {
		"adzcoin": "ADZ",
		"auroracoin": "AUR",
		"bitcoin": "BTC",
		"bitcoin-cash": "BCH",
		"bitcoin-gold": "BTG",
		"bitcoin-private": "BTCP",
		"dash": "DSH",
		"digibyte": "DGB",
		"digibyte-groestl": "DGB",
		"digibyte-skein": "DGB",
		"digibyte-qubit": "DGB",
		"electroneum": "ETN",
		"ethereum": "ETH",
		"ethereum-classic": "ETC",
		"expanse": "EXP",
		"feathercoin": "FTC",
		"gamecredits": "GAME",
		"geocoin": "GEO",
		"globalboosty": "BSTY",
		"groestlcoin": "GRS",
		"litecoin": "LTC",
		"maxcoin": "MAX",
		"monacoin": "MONA",
		"monero": "XMR",
		"musicoin": "MUSIC",
		"myriadcoin": "XMY",
		"myriadcoin-skein": "XMY",
		"myriadcoin-groestl": "XMY",
		"myriadcoin-yescrypt": "XMY",
		"sexcoin": "SXC",
		"siacoin": "SC",
		"startcoin": "START",
		"verge": "XVG",
		"vertcoin": "VTC",
		"zcash": "ZEC",
		"zclassic": "ZCL",
		"zcoin": "XZC",
		"zencash": "ZEN"
	},
	"ghpages-baseurl": "/miningprofit"
}
